import UserWrapper from '@/app/UserWrapper'
import Layout from '@/components/Layout'
import '../../styles/globals.css'

export const metadata = {
  title: 'kerman-kartkhan',
  description: 'Generated by create next app',
  icons: '/images/browser-tab-logo.png',
}

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body className="bg-bg overflow-x-hidden">
        <UserWrapper>
          <Layout>{children}</Layout>
        </UserWrapper>
      </body>
    </html>
  )
}
